### PR TITLE
fix: improve `XMLHttpRequestInterceptor` event target

### PR DESCRIPTION
**Pull request by typed-sigterm**
Sorry to bother you. I found that #22 was not suitable for all situations, so I made this one :) tested on my machine

### CODE REVIEW

**Comment by huturen** [comment]
@typed-sigterm 

There are two ESLint issue warnings in this pull request. It would be helpful if you could address it.

image

image

**Comment by typed-sigterm** [comment]
Done :)

**Comment by huturen** [comment]
Merged.

**Comment by huturen** [comment]
The version has been released to [1.8.27](https://www.npmjs.com/package/http-request-mock/v/1.8.27).

**Pull request merged**
